site_name: The Field Guide to Open Source in the Newsroom - Spanish
pages:
    - Inicio: index.md
    - Capítulo 1 - Optar por código abierto y conseguir vistos buenos: Capitulo01-Optar-por-codigo-abierto.md
    - Capítulo 2 - Empezar un proyecto nuevo: Capitulo02-Empezar-proyecto-nuevo.md
    - Capítulo 3 - Liberar un proyecto anterior: Capitulo03-Proyectos-anteriores.md
    - Capítulo 4 - El código y cómo lanzar la primera versión: Capitulo04-Codigo-primera-version.md
    - Capítulo 5 - Documentación: Capitulo05-Documentacion.md
    - Capítulo 6 - Trabajar en comunidad: Capitulo06-Comunidad.md
    - Capítulo 7 - Administración de versiones: Capitulo07-Versiones.md
    - Capítulo 8 - Abandono y desactivación: Capitulo08-Abandono-desactivacion.md
    - Ayuda: ayuda.md
theme: readthedocs
